version: '3'
services:
  web:
    build:
      context: ../../
      dockerfile: ./sample-apps/leaky-bucket-app/Dockerfile
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/leaky-bucket-app
    entrypoint: ./docker-entrypoint.sh
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
  resque:
    build:
      context: ../../
      dockerfile: ./sample-apps/leaky-bucket-app/Dockerfile
    command: bundle exec rake environment resque:work QUEUE=*
    volumes:
      - .:/fitmo
      - ../fitmo-core:/fitmo-core