default: &default
  adapter: mysql2
  pool: 5
  username: root
  password: '!12591996Ja'
  host: localhost

development:
  <<: *default
  database: webhooks_contacts_app_development

test:
  <<: *default
  database: webhooks_contacts_app_test