version: '3'
services:
  web:
    build:
      context: ../../
      dockerfile: ./sample-apps/redis-sample-app/Dockerfile
    command: bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/redis-sample-app
    entrypoint: ./docker-entrypoint.sh
  redis:
    image: 'redis:4.0-alpine'
    command: redis-server
  sidekiq:
    build:
      context: ../../
      dockerfile: ./sample-apps/redis-sample-app/Dockerfile
    depends_on:
      - web
      - redis
    env_file: .env
    volumes:
      - .:/redis-sample-app
    entrypoint: ./sidekiq-entrypoint.sh